In [2]:
import torch
import numpy as np
import pandas as pd


if torch.cuda.is_available():
    device = torch.device("cuda")
    print("GPU is available and being used.")
    print("Device name:", torch.cuda.get_device_name(0))
else:
    device = torch.device("cpu")
    print("GPU not available, using CPU.")

try:
    x = np.arange(15).reshape(3, 5)
    print("NumPy array created successfully:")
    print(x)
    print("\nNumPy is working correctly!")
except ImportError:
    print("Error: NumPy is not installed or not working.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")


try:
    # Create a simple DataFrame
    data = {'A': [1, 2, 3], 'B': [4, 5, 6]}
    df = pd.DataFrame(data)

    # Perform a basic operation
    sum_b = df['B'].sum()

    print("Pandas is working correctly.")
    print(f"DataFrame:\n{df}")
    print(f"Sum of column B: {sum_b}")

except ImportError:
    print("Error: Pandas library not found. Please install it using 'pip install pandas'.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")


GPU is available and being used.
Device name: NVIDIA GeForce RTX 3090
NumPy array created successfully:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

NumPy is working correctly!
Pandas is working correctly.
DataFrame:
   A  B
0  1  4
1  2  5
2  3  6
Sum of column B: 15
